#! /bin/sh

if [ -x $HOME/.config/bspwm/screens.sh ]; then
	$HOME/.config/bspwm/screens.sh
fi

bspc monitor HDMI-1 -d I II III IV V 
bspc monitor eDP-1 -d VI VII VIII IX X

# Border colors
bspc config normal_border_color "#2d2d2d"
bspc config focused_border_color "#cccccc"


bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &
$HOME/.config/bspwm/background.sh &
$HOME/.config/bspwm/panel.sh &
