#!/bin/sh
# bspwm config
./dual_monitor
bspc monitor eDP -d I II III IV V
bspc monitor HDMI-A-0 -d VI VII VIII IX X

# initialize desktops
# make borders black
bspc config normal_border_color "#262425"
bspc config active_border_color "#262425"
bspc config focused_border_color "#262425"
bspc config presel_feedback_color "#262425"

# make borders bigger
bspc config border_width 0 

# make a window gap
bspc config window_gap 50
exec start-pulseaudio-x11 &
exec mpc pause &
exec polybar main &
exec sxhkd &
exec feh --bg-fill ~/Pictures/nature/henrik-donnestad-V6Qd6zA85ck-unsplash.jpg 

bspc rule -a zathura state=tiling
